version: '3'

services:
  web:
   container_name: web
   build: ./docker/images/api_nginx
   volumes:
          - ./app/api:/var/www/app/api/
          - ./oauth2/server:/var/www/app/server/
  #        - ./site.conf:/etc/nginx/conf.d/site.conf
   links:
          - php
   ports:
          - "80:80"
   expose:
          - "80"
   environment:
          - "VIRTUAL_HOST=api.mmilko.git"
          - "VIRTUAL_PORT=8080"
   networks:
    net:
      ipv4_address: 172.28.0.5
   extra_hosts:
          - "api.mmilko.git:172.28.0.5"
          - "server.oauth2.mmilko.git:172.28.0.5"
  php:
    container_name: php
    build: ./docker/images/api_php
    command: php-fpm
    volumes:
          - ./app/api:/var/www/app/api/
          - ./oauth2/server:/var/www/app/server/
    working_dir: /var/www/
    ports:
          - "9000:9000"
    links:
          - mongo
          - pgsql
          - mysql
    networks:
     net:
      ipv4_address: 172.28.0.6
    extra_hosts:
          - "api.mmilko.git:172.28.0.5"
          - "server.oauth2.mmilko.git:172.28.0.5"
  mongo:
    container_name: mongo
    build: ./docker/images/mongo
    ports:
          - "27017:27017"
    expose:
          - "27017"
    volumes:
          - ./tmp/mongo/data/db:/data/db
    restart: always
    networks:
     net:
       ipv4_address: 172.28.0.4
  pgsql:
    container_name: pgsql
    build: ./docker/images/pgsql
    ports:
          - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=
      - DB_PASS=
      - DB_NAME=
      - DB_TEMPLATE=
      - DB_EXTENSION=
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    networks:
      net:
       ipv4_address: 172.28.0.3
    restart: always
    expose:
      - "5432"
    volumes:
      - ./tmp/pgsql/data/db:/var/lib/postgresql
  mysql:
    container_name: mysql
    build: ./docker/images/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
      - MYSQL_DATABASE="oauth2"
    networks:
     net:
      ipv4_address: 172.28.0.2
    expose:
      - "3306"
    volumes:
      - ./tmp/mysql/data/db:/var/lib/mysql
networks:
    net:
      ipam:
          driver: bridge
          config:
              - subnet: 172.28.0.0/16